# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

variables:
 - group: MIS-DB-VAISHNAVI

pool:
 name: Azure VM Agent Pool
  # name: MIS Agent Pool
  # demands:
  #  - agent.name -equals VAISHNAVIRA-VD3
resources:
  pipelines:
     - pipeline: mis-travel-db-vaishnavi
       source: MIS-TRAVEL-DB-DEPLOY-VAISHNAVI
       trigger: true
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

stages:
 - stage: 'QA'  
   jobs:
   - job: 'QA'
     steps:
      - template: .azure/pipelines/vaishnavi/Service-Template.yml@mis-reusable
        parameters:
         azureSubscription: $(azureSubscription)
         projects: '**/MIS.Services.Customer.Api.csproj'
         keyVaultName: 'mis-keyvault-vaishn-qa'
         keyVaultResourceGroupName: $(keyVaultResourceGroupName)
         ResourceGrpName: $(resoureceGroupNameQA)    
         azureAppName: 'mis-customer-service-vaishnavi-QA'
         serviceName: 'Customer' 
         environmentName: $(environmentNameQA)

 - stage: 'Production'
   jobs:
   - job: 'Production'
     steps:
      - template: .azure/pipelines/vaishnavi/Service-Template.yml@mis-reusable
        parameters:
         azureSubscription: $(azureSubscription)
         projects: '**/MIS.Services.Customer.Api.csproj'
         keyVaultName: 'mis-keyvault-vaishn-prod'
         keyVaultResourceGroupName: $(keyVaultResourceGroupName)
         ResourceGrpName: $(resoureceGroupNameProd)    
         azureAppName: 'mis-customer-service-vaishnavi-prod'
         serviceName: 'Customer' 
         environmentName: $(environmentNameProd)
    