trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'cybage.azurecr.io'
    repository: 'mis-customer-service-vaishnavi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'