# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main
variables:
 - group: MIS-SERVICES-VAISHNAVI
pool:
 name: Azure VM Agent Pool
  # name: MIS Agent Pool
  # demands:
  #  - agent.name -equals VAISHNAVIRA-VD3
resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/vaishnavi/Service-Template.yml@mis-reusable
    parameters:
     azureSubscription: $(azureSubscription)
     projects: '**/MIS.Services.Customer.Api.csproj'
     appName: 'mis-customer-service-vaishnavi'
     
     