# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none
pool:
   name: MIS Agent Pool
   demands:
    - agent.name -equals self-hosted-agent-Rk
resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main

steps:
  - template: .azure/pipelines/ravi/MIS-SVC-REUSABLE-IIS-RK.yml@mis-reusable
    parameters:
     projects: '**/MIS.Services.Customer.Api/MIS.Services.Customer.Api.csproj'
     WebsiteName: 'mis-customer-service'