name: CUSTOMER-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)

pool: 
 name: Azure VM Agent Pool
 demands:
    - agent.name -equals Azure-Linux-VM-Agent-1
stages:
  - stage: Build
    displayName: Build and Push
    jobs:
      - job: Build
        displayName: Build
        steps:
                   
        - task: Docker@2
          inputs:
            containerRegistry: $(containerRegistryName)
            repository: mis-customer-service-shriviraj
            tags: |
                latest
                $(Build.BuildNumber)
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'