name: IIS-CUSTOMER-SERVICE-DEPLOY-$(Year:yyyy).$(Month).$(DayOfMonth)-$(rev:rr)

trigger:
- none

pool: 
 name: MIS Agent Pool
 demands:
    - agent.name -equals SHRIVIRAJA-VD3

resources:
  repositories:
    - repository: mis-reusable
      type: github
      name: cybagedevops/mis-reusable
      endpoint: mis
      ref: main
    
steps:
  - template: .azure/pipelines/shriviraj/IISServiceDeployTemplate.yml@mis-reusable
    parameters:
     projects: '**/MIS.Services.Customer.Api.csproj'
     WebsiteName: 'mis-customer-service'
     port: '8036'