name: customer-service-cd-yash
on:
  workflow_run:
    workflows: ["customer-service-ci-yash"]
    types:
      - completed

jobs:
    Deploy:
     
      uses: cybagedevops/mis-reusable/.github/workflows/mis-service-reusable-template-cd-yash.yaml@main
      with:
          artifact-name: 'customer-service'
          app-name: 'mis-customer-svc-yash-prod'
          appSettings: 'yashProd'
          keyVaultName: 'mis-keyvault-yashdu'
          resourceGroupNameKeyVault: 'rg-mis-persistent'
          repository-name: 'cybagedevops/mis-customer-service'
          resource-group: 'rg-mis-yash-prod'
      secrets: inherit
          