name: Dotnet Image to ACR

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
      
    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
          login-server: cybage.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
           
          
    - name: Build and Push   
      run: |
          
          docker build . -t cybage.azurecr.io/mis.service.cus:latest
          docker push cybage.azurecr.io/mis.service.cus:latest
          docker build . -t cybage.azurecr.io/mis.service.cus:$(date +'%Y.%m.%d.${{github.run_number}}')
          docker push cybage.azurecr.io/mis.service.cus:$(date +'%Y.%m.%d.${{github.run_number}}')
