name: main-pullrequest-statuscheck

on: 
    repository_dispatch:
        types: [build]
    workflow_dispatch:
    pull_request:
      branches:
       - main


jobs:
  Build-CI-Pull:
     uses: cybagedevops/mis-reusable/.github/workflows/build.yml@main
     with:
            SERVICE_NAME: Mis.Services.Customer.Api
